name: CI/CD-Pipeline-to-AWS-ElasticBeanstalk

env:
  EB_PACKAGE_S3_BUCKET_NAME: "siarhei-kvachenok-github-actions-pipeline"
  EB_APPLICATION_NAME: "GithubActionsPipeline"
  EB-ENVIRONMENT_NAME: "development"
  DEPLOY_PACKAGE_NAME: "react_app_github_actions_${{ gitnub.sha }}.zip"
  AWS_REGION_NAME: "us-east-2"
  

on:
  push:
    branches:
      - master

jobs:
  ci-part:
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone repo
        uses: actions/checkout@v1
    
      - name: Create ZIP deployment package
        run: zip -r ${{ DEPLOY_PACKAGE_NAME }} ./ -x *.git*
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}
          
      - name: Copy Deployment package to S3 bucket
        run: aws cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}
      
      - name: CI completed
        run: echo "CI Pipeline finished successfully!"
      
      
        
        
